In [3]:
import numpy as np
import pandas as pd

from sklearn.model_selection import KFold , cross_val_score
from sklearn.linear_model import LinearRegression, Ridge
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import OneHotEncoder, StandardScaler, OrdinalEncoder
from sklearn.compose import ColumnTransformer

from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_absolute_error

from sklearn.decomposition import PCA

In [4]:
df = pd.read_csv('gurgaon_properties_post_feature_selection_v2.csv').drop(columns =['store room', 'floor_category','balcony'])

In [5]:
df.columns

Index(['property_type', 'sector', 'price', 'bedRoom', 'bathroom',
       'agePossession', 'built_up_area', 'servant room', 'furnishing_type',
       'luxury_category'],
      dtype='object')

In [6]:
df

,property_type,sector,price,bedRoom,bathroom,agePossession,built_up_area,servant room,furnishing_type,luxury_category
0,flat,sector 68,1.90,3,3,Under Construction,2288.0,1,0,Low
1,flat,sector 84,2.28,4,4,Relatively New,2998.0,1,0,Medium
2,flat,sector 68,1.10,2,2,Relatively New,1150.0,0,1,Medium
3,house,sector 67,8.00,6,7,Moderately Old,3600.0,1,1,High
4,flat,sector 56,1.54,3,4,Old Property,1900.0,1,0,Medium
...,...,...,...,...,...,...,...,...,...,...
3539,house,sector 48,5.15,5,7,Moderately Old,2727.0,1,1,Medium
3540,house,sector 39,1.70,2,2,Moderately Old,900.0,1,0,Low
3541,flat,sector 89,1.85,3,3,New Property,1946.0,1,0,Low
3542,flat,sector 2,0.56,1,2,Moderately Old,723.0,0,0,Medium
3543,house,sector 17b,7.20,4,4,Old Property,4521.0,1,0,Low

In [7]:
# 0 --> unfurnished
# 1 --> semifurnished
# 2 --> furnished

In [8]:
# Numerical = bedRoom, bathroom, built_up_area, sevant room
# Ordinal = property_type, furnishing_type, Luxury_category
# OHE = sector, agePossession

In [9]:
df['agePossession'] = df['agePossession'].replace({
    'Relatively New' : 'new',
    'Moderately Old' : 'old',
    'New Property' : 'new',
    'Old Property' : 'old',
    'Under Construction' : 'under construction'
})

In [10]:
df.head()

,property_type,sector,price,bedRoom,bathroom,agePossession,built_up_area,servant room,furnishing_type,luxury_category
0,flat,sector 68,1.90,3,3,under construction,2288.0,1,0,Low
1,flat,sector 84,2.28,4,4,new,2998.0,1,0,Medium
2,flat,sector 68,1.10,2,2,new,1150.0,0,1,Medium
3,house,sector 67,8.00,6,7,old,3600.0,1,1,High
4,flat,sector 56,1.54,3,4,old,1900.0,1,0,Medium

In [11]:
df['property_type'] = df['property_type'].replace({'flat':0,'house':1})

C:\Users\Mr\AppData\Local\Temp\ipykernel_15440\71934247.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df['property_type'] = df['property_type'].replace({'flat':0,'house':1})

In [12]:
df.head()

,property_type,sector,price,bedRoom,bathroom,agePossession,built_up_area,servant room,furnishing_type,luxury_category
0,0,sector 68,1.90,3,3,under construction,2288.0,1,0,Low
1,0,sector 84,2.28,4,4,new,2998.0,1,0,Medium
2,0,sector 68,1.10,2,2,new,1150.0,0,1,Medium
3,1,sector 67,8.00,6,7,old,3600.0,1,1,High
4,0,sector 56,1.54,3,4,old,1900.0,1,0,Medium

In [13]:
df['luxury_category'] = df['luxury_category'].replace({'Low':0,'Medium':1,'High':2})

C:\Users\Mr\AppData\Local\Temp\ipykernel_15440\2576796079.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df['luxury_category'] = df['luxury_category'].replace({'Low':0,'Medium':1,'High':2})

In [14]:
df.head()

,property_type,sector,price,bedRoom,bathroom,agePossession,built_up_area,servant room,furnishing_type,luxury_category
0,0,sector 68,1.90,3,3,under construction,2288.0,1,0,0
1,0,sector 84,2.28,4,4,new,2998.0,1,0,1
2,0,sector 68,1.10,2,2,new,1150.0,0,1,1
3,1,sector 67,8.00,6,7,old,3600.0,1,1,2
4,0,sector 56,1.54,3,4,old,1900.0,1,0,1

In [15]:
new_df = pd.get_dummies(df,columns=['sector','agePossession'], drop_first=True)

In [16]:
x = new_df.drop(columns=['price'])
y = new_df['price']

In [17]:
y_log = np.log1p(y)

In [18]:
y_log

0       1.064711
1       1.187843
2       0.741937
3       2.197225
4       0.932164
          ...
3539    1.816452
3540    0.993252
3541    1.047319
3542    0.444686
3543    2.104134
Name: price, Length: 3544, dtype: float64

In [19]:
scaler = StandardScaler()

X_scaled = scaler.fit_transform(x)

In [20]:
X_scaled = pd.DataFrame(X_scaled, columns=x.columns)

In [21]:
X_scaled

,property_type,bedRoom,bathroom,built_up_area,servant room,furnishing_type,luxury_category,sector_gwal pahari,sector_manesar,sector_new,...,sector_sector 92,sector_sector 93,sector_sector 95,sector_sector 99,sector_sector 99a,sector_sector 9a,sector_sohna road,sector_sohna road road,agePossession_old,agePossession_under construction
0,-0.514598,-0.068828,-0.180233,0.374772,1.339758,-0.558784,-0.981828,-0.071449,-0.093938,-0.033615,...,-0.169521,-0.050458,-0.125554,-0.058288,-0.092397,-0.053194,-0.210958,-0.053194,-0.603429,3.441014
1,-0.514598,0.744264,0.515568,0.965597,1.339758,-0.558784,0.442486,-0.071449,-0.093938,-0.033615,...,-0.169521,-0.050458,-0.125554,-0.058288,-0.092397,-0.053194,-0.210958,-0.053194,-0.603429,-0.290612
2,-0.514598,-0.881921,-0.876034,-0.572213,-0.746403,1.220489,0.442486,-0.071449,-0.093938,-0.033615,...,-0.169521,-0.050458,-0.125554,-0.058288,-0.092397,-0.053194,-0.210958,-0.053194,-0.603429,-0.290612
3,1.943265,2.370449,2.602971,1.466550,1.339758,1.220489,1.866800,-0.071449,-0.093938,-0.033615,...,-0.169521,-0.050458,-0.125554,-0.058288,-0.092397,-0.053194,-0.210958,-0.053194,1.657196,-0.290612
4,-0.514598,-0.068828,0.515568,0.051898,1.339758,-0.558784,0.442486,-0.071449,-0.093938,-0.033615,...,-0.169521,-0.050458,-0.125554,-0.058288,-0.092397,-0.053194,-0.210958,-0.053194,1.657196,-0.290612
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3539,1.943265,1.557357,2.602971,0.740085,1.339758,1.220489,0.442486,-0.071449,-0.093938,-0.033615,...,-0.169521,-0.050458,-0.125554,-0.058288,-0.092397,-0.053194,-0.210958,-0.053194,1.657196,-0.290612
3540,1.943265,-0.881921,-0.876034,-0.780250,1.339758,-0.558784,-0.981828,-0.071449,-0.093938,-0.033615,...,-0.169521,-0.050458,-0.125554,-0.058288,-0.092397,-0.053194,-0.210958,-0.053194,1.657196,-0.290612
3541,-0.514598,-0.068828,-0.180233,0.090177,1.339758,-0.558784,-0.981828,-0.071449,-0.093938,-0.033615,...,-0.169521,-0.050458,-0.125554,-0.058288,-0.092397,-0.053194,-0.210958,-0.053194,-0.603429,-0.290612
3542,-0.514598,-1.695013,-0.876034,-0.927540,-0.746403,-0.558784,0.442486,-0.071449,-0.093938,-0.033615,...,-0.169521,-0.050458,-0.125554,-0.058288,-0.092397,-0.053194,-0.210958,-0.053194,1.657196,-0.290612
3543,1.943265,0.744264,0.515568,2.232958,1.339758,-0.558784,-0.981828,-0.071449,-0.093938,-0.033615,...,-0.169521,-0.050458,-0.125554,-0.058288,-0.092397,-0.053194,-0.210958,-0.053194,1.657196,-0.290612

In [22]:
kfold = KFold(n_splits=10, shuffle=True, random_state=42)
scores = cross_val_score(LinearRegression(), X_scaled, y_log, cv=kfold, scoring='r2')

In [23]:
scores.mean(),scores.std()

(0.8505181753677478, 0.02100049332328092)

In [24]:
lr = LinearRegression()
ridge = Ridge(alpha=0.0001)

In [25]:
lr.fit(X_scaled,y_log)

LinearRegression()

In [26]:
ridge.fit(X_scaled,y_log)

Ridge(alpha=0.0001)

In [29]:
coef_df = pd.DataFrame(ridge.coef_.reshape(1,123), columns=x.columns).stack().reset_index().drop(columns=['level_0']).rename(columns={'level_1':'feature',0:'coef'})

In [30]:
coef_df

                              feature      coef
0                       property_type  0.126121
1                             bedRoom  0.055983
2                            bathroom  0.064933
3                       built_up_area  0.207906
4                        servant room  0.048618
..                                ...       ...
118                  sector_sector 9a -0.005100
119                 sector_sohna road -0.026772
120            sector_sohna road road -0.011944
121                 agePossession_old -0.008544
122  agePossession_under construction  0.015142

[123 rows x 2 columns]

In [31]:
# 1. Import necessary libraries
import statsmodels.api as sm

# 2. Add a constant to X
X_with_const = sm.add_constant(X_scaled)


# 3. Fit the model
model = sm.OLS(y_log, X_with_const).fit()

# 4. Obtain summary statistics
print(model.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:                  price   R-squared:                       0.866
Model:                            OLS   Adj. R-squared:                  0.861
Method:                 Least Squares   F-statistic:                     179.6
Date:                Wed, 01 Apr 2026   Prob (F-statistic):               0.00
Time:                        22:21:32   Log-Likelihood:                 618.73
No. Observations:                3544   AIC:                            -989.5
Df Residuals:                    3420   BIC:                            -224.0
Df Model:                         123
Covariance Type:            nonrobust
=====================================================================================================
                                        coef    std err          t      P>|t|      [0.025      0.975]
-----------------------------------------------------------------------------------------------------
const                                 1.0438      0.003    300.390      0.000       1.037       1.051
property_type                         0.1261      0.005     23.825      0.000       0.116       0.136
bedRoom                               0.0560      0.007      8.581      0.000       0.043       0.069
bathroom                              0.0649      0.007      9.587      0.000       0.052       0.078
built_up_area                         0.2079      0.005     41.226      0.000       0.198       0.218
servant room                          0.0486      0.005     10.745      0.000       0.040       0.057
furnishing_type                       0.0115      0.004      2.881      0.004       0.004       0.019
luxury_category                       0.0038      0.004      0.948      0.343      -0.004       0.012
sector_gwal pahari                    0.0102      0.006      1.621      0.105      -0.002       0.023
sector_manesar                       -0.0223      0.008     -2.890      0.004      -0.037      -0.007
sector_new                           -0.0031      0.004     -0.725      0.469      -0.011       0.005
sector_new sector 2                  -0.0038      0.004     -0.858      0.391      -0.013       0.005
sector_sector 1                      -0.0054      0.005     -1.178      0.239      -0.015       0.004
sector_sector 102                     0.0281      0.013      2.146      0.032       0.002       0.054
sector_sector 103                    -0.0024      0.009     -0.273      0.785      -0.019       0.015
sector_sector 104                     0.0030      0.011      0.285      0.776      -0.018       0.024
sector_sector 105                    -0.0199      0.007     -3.016      0.003      -0.033      -0.007
sector_sector 106                     0.0014      0.008      0.162      0.872      -0.015       0.018
sector_sector 107                    -0.0123      0.010     -1.225      0.221      -0.032       0.007
sector_sector 108                     0.0177      0.010      1.770      0.077      -0.002       0.037
sector_sector 109                     0.0259      0.012      2.173      0.030       0.003       0.049
sector_sector 10a                     0.0051      0.005      1.069      0.285      -0.004       0.015
sector_sector 11                     -0.0152      0.006     -2.488      0.013      -0.027      -0.003
sector_sector 110                     0.0129      0.007      1.872      0.061      -0.001       0.026
sector_sector 111                     0.0167      0.007      2.479      0.013       0.003       0.030
sector_sector 112                     0.0314      0.007      4.548      0.000       0.018       0.045
sector_sector 113                     0.0329      0.009      3.747      0.000       0.016       0.050
sector_sector 12                     -0.0198      0.008     -2.534      0.011      -0.035      -0.004
sector_sector 13                     -0.0132      0.005     -2.653      0.008      -0.023      -0.003
sector_sector 14                      0.0278      0.006      4.387      0.000       0.015       0.040
sector_sector 15                      0.0051      0.005      1.094      0.274      -0.004       0.014
sector_sector 17                      0.0063      0.005      1.351      0.177      -0.003       0.015
sector_sector 17a                     0.0037      0.004      1.010      0.313      -0.004       0.011
sector_sector 17b                     0.0130      0.004      3.157      0.002       0.005       0.021
sector_sector 2                       0.0073      0.010      0.712      0.476      -0.013       0.027
sector_sector 21                     -0.0088      0.005     -1.891      0.059      -0.018       0.000
sector_sector 22                      0.0354      0.007      5.420      0.000       0.023       0.048
sector_sector 23                      0.0013      0.006      0.226      0.821      -0.010       0.012
sector_sector 24                      0.0175      0.007      2.666      0.008       0.005       0.030
sector_sector 25                      0.0577      0.008      6.970      0.000       0.041       0.074
sector_sector 26                      0.0723      0.009      8.357      0.000       0.055       0.089
sector_sector 27                      0.0061      0.004      1.555      0.120      -0.002       0.014
sector_sector 28                      0.0429      0.008      5.108      0.000       0.026       0.059
sector_sector 3                      -0.0111      0.007     -1.578      0.115      -0.025       0.003
sector_sector 3 phase 2              -0.0109      0.005     -2.367      0.018      -0.020      -0.002
sector_sector 3 phase 3 extension    -0.0140      0.005     -2.734      0.006      -0.024      -0.004
sector_sector 30                      0.0063      0.004      1.413      0.158      -0.002       0.015
sector_sector 31                      0.0220      0.005      4.182      0.000       0.012       0.032
sector_sector 33                      0.0262      0.011      2.477      0.013       0.005       0.047
sector_sector 36                     -0.0070      0.005     -1.303      0.193      -0.018       0.004
sector_sector 36a                     0.0107      0.005      1.995      0.046       0.000       0.021
sector_sector 37                     -0.0026      0.004     -0.691      0.489      -0.010       0.005
sector_sector 37c                    -0.0109      0.009     -1.152      0.249      -0.029       0.008
sector_sector 37d                     0.0015      0.010      0.147      0.883      -0.019       0.022
sector_sector 38                      0.0119      0.005      2.264      0.024       0.002       0.022
sector_sector 39                      0.0020      0.005      0.363      0.717      -0.009       0.013
sector_sector 4                      -0.0194      0.009     -2.151      0.032      -0.037      -0.002
sector_sector 40                      0.0081      0.004      1.800      0.072      -0.001       0.017
sector_sector 41                      0.0161      0.005      2.971      0.003       0.005       0.027
sector_sector 43                      0.0611      0.010      6.181      0.000       0.042       0.080
sector_sector 45                      0.0263      0.005      5.295      0.000       0.017       0.036
sector_sector 46                      0.0164      0.005      3.009      0.003       0.006       0.027
sector_sector 47                      0.0130      0.006      2.137      0.033       0.001       0.025
sector_sector 48                      0.0523      0.010      5.358      0.000       0.033       0.071
sector_sector 49                      0.0316      0.009      3.509      0.000       0.014       0.049
sector_sector 5                      -0.0037      0.005     -0.800      0.424      -0.013       0.005
sector_sector 50                      0.0702      0.010      6.850      0.000       0.050       0.090
sector_sector 51                      0.0011      0.005      0.236      0.814      -0.008       0.011
sector_sector 52                      0.0046      0.006      0.800      0.424      -0.007       0.016
sector_sector 53                      0.0477      0.006      8.261      0.000       0.036       0.059
sector_sector 54                      0.0456      0.007      6.308      0.000       0.031       0.060
sector_sector 55                      0.0133      0.005      2.517      0.012       0.003       0.024
sector_sector 56                      0.0119      0.010      1.240      0.215      -0.007       0.031
sector_sector 57                      0.0247      0.007      3.618      0.000       0.011       0.038
sector_sector 58                      0.0237      0.005      4.953      0.000       0.014       0.033
sector_sector 59                      0.0320      0.005      6.499      0.000       0.022       0.042
sector_sector 6                      -0.0163      0.005     -3.014      0.003      -0.027      -0.006
sector_sector 60                      0.0241      0.006      4.053      0.000       0.012       0.036
sector_sector 61                      0.0371      0.009      4.337      0.000       0.020       0.054
sector_sector 62                      0.0434      0.006      7.176      0.000       0.032       0.055
sector_sector 63                      0.0349      0.006      6.026      0.000       0.024       0.046
sector_sector 63a                     0.0237      0.006      4.023      0.000       0.012       0.035
sector_sector 65                      0.0725      0.012      6.117      0.000       0.049       0.096
sector_sector 66                      0.0529      0.009      6.118      0.000       0.036       0.070
sector_sector 67                      0.0411      0.009      4.491      0.000       0.023       0.059
sector_sector 67a                     0.0102      0.007      1.540      0.124      -0.003       0.023
sector_sector 68                      0.0111      0.008      1.467      0.143      -0.004       0.026
sector_sector 69                      0.0192      0.012      1.570      0.117      -0.005       0.043
sector_sector 7                      -0.0025      0.008     -0.302      0.763      -0.018       0.014
sector_sector 70                      0.0061      0.009      0.655      0.512      -0.012       0.024
sector_sector 70a                     0.0172      0.010      1.770      0.077      -0.002       0.036
sector_sector 71                     -0.0027      0.007     -0.365      0.715      -0.017       0.012
sector_sector 72                      0.0304      0.008      4.039      0.000       0.016       0.045
sector_sector 73                     -0.0016      0.004     -0.381      0.703      -0.010       0.006
sector_sector 74                      0.0226      0.006      3.585      0.000       0.010       0.035
sector_sector 76                     -0.0003      0.006     -0.057      0.954      -0.012       0.011
sector_sector 77                      0.0012      0.007      0.162      0.871      -0.013       0.015
sector_sector 78                     -0.0040      0.006     -0.657      0.511      -0.016       0.008
sector_sector 79                      0.0140      0.011      1.257      0.209      -0.008       0.036
sector_sector 8                      -0.0126      0.005     -2.623      0.009      -0.022      -0.003
sector_sector 80                      0.0005      0.004      0.117      0.907      -0.008       0.009
sector_sector 81                      0.0160      0.012      1.338      0.181      -0.007       0.039
sector_sector 82                      0.0008      0.009      0.096      0.924      -0.016       0.018
sector_sector 82a                     0.0096      0.006      1.500      0.134      -0.003       0.022
sector_sector 83                      0.0004      0.011      0.037      0.971      -0.021       0.021
sector_sector 84                     -0.0098      0.009     -1.054      0.292      -0.028       0.008
sector_sector 85                      0.0092      0.013      0.709      0.478      -0.016       0.035
sector_sector 86                     -0.0032      0.010     -0.312      0.755      -0.023       0.017
sector_sector 88a                     0.0080      0.007      1.205      0.228      -0.005       0.021
sector_sector 88b                     0.0001      0.004      0.030      0.976      -0.008       0.008
sector_sector 89                      0.0023      0.010      0.238      0.812      -0.017       0.022
sector_sector 9                      -0.0122      0.006     -2.187      0.029      -0.023      -0.001
sector_sector 90                     -0.0097      0.012     -0.806      0.420      -0.033       0.014
sector_sector 91                  -4.272e-05      0.006     -0.007      0.994      -0.012       0.012
sector_sector 92                     -0.0276      0.013     -2.185      0.029      -0.052      -0.003
sector_sector 93                     -0.0040      0.005     -0.789      0.430      -0.014       0.006
sector_sector 95                     -0.0246      0.010     -2.524      0.012      -0.044      -0.006
sector_sector 99                      0.0017      0.006      0.306      0.759      -0.009       0.012
sector_sector 99a                    -0.0126      0.008     -1.665      0.096      -0.028       0.002
sector_sector 9a                     -0.0051      0.005     -0.971      0.332      -0.015       0.005
sector_sohna road                    -0.0268      0.015     -1.751      0.080      -0.057       0.003
sector_sohna road road               -0.0119      0.005     -2.280      0.023      -0.022      -0.002
agePossession_old                    -0.0085      0.005     -1.716      0.086      -0.018       0.001
agePossession_under construction      0.0151      0.004      3.762      0.000       0.007       0.023
==============================================================================
Omnibus:                      529.699   Durbin-Watson:                   1.998
Prob(Omnibus):                  0.000   Jarque-Bera (JB):             5676.300
Skew:                          -0.348   Prob(JB):                         0.00
Kurtosis:                       9.161   Cond. No.                         40.0
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.

In [32]:
y_log.std()

0.5551372282244343

In [33]:
X_scaled['bedRoom'].std()

1.0001411133853069

In [34]:
0.21 * (0.557/1)

0.11697

In [35]:
np.expm1(0.030)

0.030454533953516858

In [36]:
2.4726962617564903e-05 * 100

0.0024726962617564905